### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chaffee007** [Power-Maverick/DataverseDevTools-VSCode#100]
### What happened?

![image](https://user-images.githubusercontent.com/16105932/224400740-664adfbb-1faf-4ed0-ade8-49bb3ef147e2.png)

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.76

### Any relevant session id from VSCode?

6be66883-389b-4f0b-898a-b124c9a2449e1678473518914

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: EADDRINUSE. 
Error message: listen EADDRINUSE: address already in use 127.0.0.1:19472. 
Error stack: Error: listen EADDRINUSE: address already in use 127.0.0.1:19472
	at Server.setupListenHandle [as _listen2] (node:net:1330:16)
	at listenInCluster (node:net:1378:12)
	at doListen (node:net:1516:7)
	at process.processTicksAndRejections (node:internal/process/task_queues:84:21).
```

**Comment by Power-Maverick** [comment]
Please close any other application using port 19472 as I am using it to authenticate the user which is causing conflicts.
