### ISSUE TITLE
[Bug]: Cannot connect to D365

### ISSUE THREAD

**Issue by lalberto8085** [Power-Maverick/DataverseDevTools-VSCode#101]
### What happened?

I am testing the tool on an environment that requires the use of MS Authenticator to log in and get the error

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.76.2

### Any relevant session id from VSCode?

06c045d4-7450-45d2-b253-af04cd7cfdb41679589087847

### Relevant log output

```shell
Error occured in addConnection command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Please mention which type of authentication you are using. Try Azure or Microsoft Prompt Login
