### ISSUE TITLE
[Bug]: Error when logging in using Microsoft Login

### ISSUE THREAD

**Issue by dunkhi** [Power-Maverick/DataverseDevTools-VSCode#103]
### What happened?

Tried logging in after inputting url and username/password.

### What version of the tool are you using?

2.1.1

### Any relevant session id from VSCode?

465675e9-0ff5-42ac-a199-70631de437911681247518203

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: EADDRINUSE. 
Error message: listen EADDRINUSE: address already in use 127.0.0.1:19472. 
Error stack: Error: listen EADDRINUSE: address already in use 127.0.0.1:19472
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at doListen (node:net:1516:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21).
```

**Comment by Power-Maverick** [comment]
Please close any other application using port 19472 as I am using it to authenticate the user which is causing conflicts.
