### ISSUE TITLE
[Bug]: When generating typings for a table, status code and status reason are missing from entity enum

### ISSUE THREAD

**Issue by uofirob** [Power-Maverick/DataverseDevTools-VSCode#104]
### What happened?

Trying to check a value of the status reason or status code using the display name, but when you generate typings, the values aren't added to the entityEnum that's generated from typings, so I'm unable to compare to the metadata.

### What version of the tool are you using?

v2.1.1

### What version of Visual Studio Code are you running?

1.77.3

**Comment by Power-Maverick** [comment]
Update to newer version
