### ISSUE TITLE
[Bug]: No entities found

### ISSUE THREAD

**Issue by Atili0** [Power-Maverick/DataverseDevTools-VSCode#105]
### What happened?

I already connected to the dataverser (see emage)

![image](https://user-images.githubusercontent.com/5795436/232300293-4291ee5a-1b5b-4268-9eae-d8f1daee55bd.png)

but when i tried to generated the typings a im getting this error

![image](https://user-images.githubusercontent.com/5795436/232300325-13ef9785-d1fd-454c-96c7-ff0b08c4736d.png)

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.77.3

**Comment by Power-Maverick** [comment]
Are you sure the user you are trying to login with has the permission to read the metadata?
