### ISSUE TITLE
[Bug]: Dataverse DevTools: Error occured - undefined.

### ISSUE THREAD

**Issue by vantruonginfo** [Power-Maverick/DataverseDevTools-VSCode#111]
### What happened?

I select the js file, then click on the light bulb icon, and the error message popup "Dataverse DevTools: Error occured - undefined. Please report it on GitHub.".

### What version of the tool are you using?

2.2.2

### What version of Visual Studio Code are you running?

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Any relevant session id from VSCode?

2f640db8-3338-4a59-a3c3-a6879b2e89961684141946359

### Relevant log output

```shell
Error occured in smartMatch command. 
Error code: undefined. 
Error message: spawn EPERM. 
Error stack: Error: spawn EPERM
    at M (vscode-file://vscode-app/c:/Users/Van Truong/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1829:6480)
    at vscode-file://vscode-app/c:/Users/Van Truong/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1837:4256
    at async vscode-file://vscode-app/c:/Users/Van Truong/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1837:2747.
```

**Comment by Power-Maverick** [comment]
Looks like the workspace was not granted access when prompted which resulted in this error. Closing this issue but feel free to re-open if this is still an issue.
