### ISSUE TITLE
[Bug]: Can't connect to Dataverse Devtools via "Username/Password"

### ISSUE THREAD

**Issue by Kion01** [Power-Maverick/DataverseDevTools-VSCode#125]
### What happened?

I can't connect to Dataverse Devtools via "Username/Password"

### What version of the tool are you using?

2.1.4

### What version of Visual Studio Code are you running?

1.79.2

### Any relevant session id from VSCode?

9e44946a-e675-4e44-94c4-98049be16ee51687767110164

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Based on the error looks like you are not using the right combination. Please ensure correct credentials are used. If MFA is enabled on the account then using other available options. Closing this issue but feel free to re-open if this is still an issue.
