### ISSUE TITLE
[Bug]: could not connevt to dataverse enviroment using username and password

### ISSUE THREAD

**Issue by minamzakhary** [Power-Maverick/DataverseDevTools-VSCode#132]
### What happened?

Dataverse DevTools: Error occured - undefined. Please report it on GitHub.

### What version of the tool are you using?

v2.1.4

### Any relevant session id from VSCode?

2a82bf97-4cf3-485b-a5c7-15aef0c2fcd61695732706608

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Does the credentials with which you are trying to connect has MFA enabled? If so username/password won't work.

**Comment by Power-Maverick** [comment]
Try the newer version v2.1.5

**Comment by Power-Maverick** [comment]
Not resolved.. WIP

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.

**Comment by minamzakhary** [comment]
It’s working nowThank you 


Sent from Yahoo Mail for iPhone


On Friday, October 6, 2023, 7:51 AM, Danish Naglekar ***@***.***> wrote:




Does the credentials with which you are trying to connect has MFA enabled? If so username/password won't work.
