### ISSUE TITLE
[Bug]: Error while connecting the TypeScript to the dynamic crm environment.

### ISSUE THREAD

**Issue by Vijay260** [Power-Maverick/DataverseDevTools-VSCode#133]
### What happened?

Error while connecting the TypeScript to the dynamic CRM environment.

### What version of the tool are you using?

latest

### Any relevant session id from VSCode?

c6ab0d4c-8efc-4016-adfd-f6a246905b691696309981330

### Relevant log output

```shell
Error occured in initTS command. 
Error code: undefined. 
Error message: Cannot overwrite non-directory 'c:\Users\VKumar\OneDrive - proMX AG\Vijay\Learning\Code\JS
```

**Comment by Power-Maverick** [comment]
Can you please specify exact version? Thanks 🙏

**Comment by Power-Maverick** [comment]
Try the newer version 2.1.5

**Comment by Power-Maverick** [comment]
Not resolved.. WIP

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
