### ISSUE TITLE
[Bug]: Error on every command: Command not found on latest vsCode version

### ISSUE THREAD

**Issue by Harl3** [Power-Maverick/DataverseDevTools-VSCode#134]
### What happened?

The extension stopped working after updating to the latest VsCode version, every button clicked gives a "command not found" error, for example trying to refresh connections:

dvdt.explorer.connections.refreshConnection: command 'dvdt.explorer.connections.refreshConnection' not found. This is likely caused by the extension that contributes dvdt.explorer.connections.refreshConnection.

I had to revert to VsCode 1.82 to restore a working version of the extension

![image](https://github.com/Power-Maverick/DataverseDevTools-VSCode/assets/44983299/352717e3-0646-4e87-b916-68cf95557bdd)

### What version of the tool are you using?

v2.1.4

### What version of Visual Studio Code are you running?

1.83

### Relevant log output

```shell
dvdt.explorer.connections.refreshConnection: command 'dvdt.explorer.connections.refreshConnection' not found. This is likely caused by the extension that contributes dvdt.explorer.connections.refreshConnection.
```

**Comment by DesuNinshu** [comment]
I am also facing this issue.

**Comment by Power-Maverick** [comment]
I will look into it this weekend. Thanks for letting me know.

**Comment by Power-Maverick** [comment]
I hope the issue has been resolved. Upgrade to v2.1.5. 
Please lemme know if you are running into issues.

**Comment by Power-Maverick** [comment]
Not resolved.. WIP

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
