### ISSUE TITLE
[Bug]: Unable to Activate Dataverse DevTools Extension

### ISSUE THREAD

**Issue by cody-nichols** [Power-Maverick/DataverseDevTools-VSCode#135]
### What happened?

I had been using Dataverse DevTools extension without issue until today.
I noticed my connections had disappeared. I tried to re-enter the connection but it failed to respond.
The VSCode Developer Tool log shows the following:

Activating extension 'danish-naglekar.dataverse-devtools' failed: \\?\c:\Users\VHAWLANICHOC\.vscode\extensions\danish-naglekar.dataverse-devtools-2.1.4\node_modules\keytar\build\Release\keytar.node is not a valid Win32 application.
\\?\c:\Users\VHAWLANICHOC\.vscode\extensions\danish-naglekar.dataverse-devtools-2.1.4\node_modules\keytar\build\Release\keytar.node.

I have tried to reinstall the extension multiple times as tried reinstalling VS Code, unfortunately without success.

### What version of the tool are you using?

2.1.4

### What version of Visual Studio Code are you running?

1.83.0

### Relevant log output

```shell
Activating extension 'danish-naglekar.dataverse-devtools' failed: \\?\c:\Users\VHAWLANICHOC\.vscode\extensions\danish-naglekar.dataverse-devtools-2.1.4\node_modules\keytar\build\Release\keytar.node is not a valid Win32 application.
\\?\c:\Users\VHAWLANICHOC\.vscode\extensions\danish-naglekar.dataverse-devtools-2.1.4\node_modules\keytar\build\Release\keytar.node.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:581
```

**Comment by Harl3** [comment]
It's probably the same as my issue: #134 
You can try to revert to vscode 1.82 to restore the extension

**Comment by Power-Maverick** [comment]
I will look into it this weekend. Thanks for letting me know.

**Comment by Power-Maverick** [comment]
I hope the issue has been resolved. Upgrade to v2.1.5. 
Please lemme know if you are running into issues.

**Comment by Power-Maverick** [comment]
Not resolved.. WIP

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
