### ISSUE TITLE
[Bug]: Can't create new connection

### ISSUE THREAD

**Issue by siggipop** [Power-Maverick/DataverseDevTools-VSCode#139]
### What happened?

Can't create new connection 

### What version of the tool are you using?

v2.1.6

### What version of Visual Studio Code are you running?

 1.83.0

### Relevant log output

```shell
Error: command 'dvdt.explorer.connections.addConnection' not found
```

**Comment by siggipop** [comment]
Have tried as admin user, uninstall/install, revert dvdt and vs code to an earlier version. running out of ideas.

**Comment by Power-Maverick** [comment]
Its wip 🚧

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
