### ISSUE TITLE
[Bug]: Error when connecting with username and password

### ISSUE THREAD

**Issue by yagasoft** [Power-Maverick/DataverseDevTools-VSCode#153]
### What happened?

Hello,
When I try to connect using a username and password to an on-premise environment, I receive the error below.
I tried domain\username and username@domain, both failed.
Dynamics is the latest version.

### What version of the tool are you using?

2.2.0

### What version of Visual Studio Code are you running?

1.85.1

### Any relevant session id from VSCode?

554def50-7d92-404d-b047-818a29c92b6a1705154185667

### Relevant log output

```shell
VSCode version: 1.85.1. 
Extension version: 2.2.0. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
The extension is not supported for on-prem org. Sorry.
