### ISSUE TITLE
Can't connect to Dataverse environment with Dataverse REST Builder extension in Visual Studio Code [Bug]: 

### ISSUE THREAD

**Issue by zakir365** [Power-Maverick/DataverseDevTools-VSCode#157]
### What happened?

I downloaded and installed Dataverse REST Builder extension within Visual Studio Code but the it doesn't connects to Dataverse environment and throws this error "Dataverse DevTools: Error occurred - ECONNREST. Please report it on GitHub"

### What version of the tool are you using?

VS Code

### What version of Visual Studio Code are you running?

1.86.2

### Any relevant session id from VSCode?

b423fa82-45eb-41ca-b2ef-777dededc95a1708589951063

### Relevant log output

```shell
VSCode version: 1.86.2. 
Extension version: 2.2.0. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Which connection method did you use?
