### ISSUE TITLE
[Bug]: Connection failed

### ISSUE THREAD

**Issue by jeromebq** [Power-Maverick/DataverseDevTools-VSCode#16]
### Contact Details

jeromebecu@hotmail.fr

### What happened?

I'm trying to connect on my dataverse environnement and i get a issue during connection. Unfortunately, I have no more log...

Maybe it's link with multi-factor authentification that is no supported ? 

![image](https://user-images.githubusercontent.com/28141874/132637073-4bc4361e-3b1d-4c03-8290-8a1a55c85db9.png)

### What version of the tool are you using?

1.0.0

### What version of Visual Studio Code are you running?

1.60.0

**Comment by Jerry406** [comment]
I have the same issue.

**Comment by bthibeault18** [comment]
I'm receiving this error as well

**Comment by Power-Maverick** [comment]
Hi, thanks for reporting. May I know more details about the connection?

- Did you use "Microsoft Login Prompt" or "Username/Password"?
- Is MFA enabled through MSFT or any third party?
- Any other relevant details on how you connect to Power Platform would be helpful.

We are working on getting this resolved, but in meantime, you can use the alternate login approach.

@mohsinonxrm

**Comment by bthibeault18** [comment]
Using Login Prompt worked! Thanks!

**Comment by Power-Maverick** [comment]
@jeromebq can you help me by answering the above posted questions? Thanks

**Comment by jeromebq** [comment]
Hello,

I used username/Password.
I have 2 differents connection one with MFA and  another without.

I can't user "Microsoft Login Prompt" because of policy of my organization, i can't approve the application.

**Comment by rasotoipc** [comment]
> Hello,
> 
> I used username/Password.
> I have 2 differents connection one with MFA and another without.
> 
> I can't user "Microsoft Login Prompt" because of policy of my organization, i can't approve the application.

I have same issue.

**Comment by P-focT** [comment]
Hello,

I got the same issues as mentioned above, I did try the following things:

1. Using Username/Password does not work, after choosing the system type the mentioned error occurs. I do have MFA enabled on that user, but don't get the Authenticator message on the phone. I think that's why it does not work.

2. I tried the prompt version, however it always pre assigns my VS Code user and addresses the AAD tenant of that user. However I must log in to a customers environment and can't find a way on changing the user that should be used (like in step 1) and/or the correct AAD tenant.

Best regards

**Comment by mohsinonxrm** [comment]
@Power-Maverick , looks like I do need to get the auth process sorted out :)
on it.

**Comment by P-focT** [comment]
@mohsinonxrm @Power-Maverick I think it would already be successful if you could add the prompt=login parameter to the Prompt Version in login.ts at line 99 (as referred to https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
Sample App (without prompt param): https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=6731de76-14a6-49ae-97bc-6eba6914391e&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F&response_mode=query&scope=openid%20offline_access%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read&state=12345
Sample App (with prompt=login param): https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=6731de76-14a6-49ae-97bc-6eba6914391e&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F&response_mode=query&scope=openid%20offline_access%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read&state=12345&prompt=login

This way I was able to enter username and password and was redirected to the correct AAD tenant.

**Comment by mohsinonxrm** [comment]
@Power-Maverick , I think let's do the above for now while I take the time to implement the proper solution with the refresh token stuff

**Comment by Power-Maverick** [comment]
@P-focT thanks for the PR to fix that minor bug. I have incorporated that change and released v1.1.5

**Comment by singh-harendra** [comment]
For me issues still occuring, I am using v1.1.6 though

**Comment by Power-Maverick** [comment]
Have done more improvements to the connection and also added the 3rd type of authentication using client id/secret. This is released in version 1.1.9. Closing this issue for now.
