### ISSUE TITLE
[Bug]: Unknown Error when trying to connect 

### ISSUE THREAD

**Issue by cwork-iquantiv** [Power-Maverick/DataverseDevTools-VSCode#162]
### What happened?

Was trying to connect to a Microsoft Dynamics endpoint and got an unknown error after authenticating.

### What version of the tool are you using?

V2.2.0

### What version of Visual Studio Code are you running?

1.89.0

### Any relevant session id from VSCode?

fb03aefd-2c59-46a8-95dc-372c68316e271715176021365

### Relevant log output

```shell
VSCode version: 1.89.0. 
Extension version: 2.2.0. 
Error occured in addConnection command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by alloylo** [comment]
Does this issue solved. I have the same problem. I am using VS Code v1.89,1
