### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by allenbarge** [Power-Maverick/DataverseDevTools-VSCode#168]
### What happened?

tried to configure a connection for DataVerse DEVTools. Created connection but once it dropped it into the list of connections it threw up the error 

### What version of the tool are you using?

2.2.0

### What version of Visual Studio Code are you running?

1.92.0

### Any relevant session id from VSCode?

3d867ad4-b10e-4627-b9df-84a67894e12e1722535033782

### Relevant log output

```shell
VSCode version: 1.92.0. 
Extension version: 2.2.0. 
Error occured in addConnection command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
So the connection exists in the Connections list but when you try to connect it throws an error?

What type of connection you used?
