### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Saugat1596** [Power-Maverick/DataverseDevTools-VSCode#169]
### What happened?

When I am trying to connect to a CDX environment using my credentials it is throwing an unknown error.

### What version of the tool are you using?

v2.0.0.0

### Any relevant session id from VSCode?

9d72a098-c39c-4b7b-8ba5-e3949ef802c11723056423301

### Relevant log output

```shell
VSCode version: 1.92.0. 
Extension version: 2.2.0. 
Error occured in addConnection command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Saugat1596** [comment]
Hello Danish, Can you please provide an update for the same

**Comment by Power-Maverick** [comment]
Which login type did you use?
