### ISSUE TITLE
[Bug]: linker file is not an xml according to standard because of version attribute

### ISSUE THREAD

**Issue by David-Cadmart** [Power-Maverick/DataverseDevTools-VSCode#171]
### What happened?

I created a PowerShell script that uses the xml generated in the `dvdt.linker.xml` file to automate some actions.
When I try to load the file as an xml I get an error. The issue is that the file has the version set like `version="1"`, but the standard says that the version must be `version="1.0"`.
I can edit the file and make the script work, but when a new link is created, the file is regenerated, and I have to change it again.

Can the xml be updated to have the version like the standard?

Thanks

### What version of the tool are you using?

v2.2.0

### What version of Visual Studio Code are you running?

1.92.1

### Any relevant session id from VSCode?

No

**Comment by Power-Maverick** [comment]
I am using fast xml parser to parse the file into xml. I'll have to check with that package if there is a config missing or if it's an issue with the package.

**Comment by David-Cadmart** [comment]
I don't know if it is relevant, but the linker file in the templates section has the correct value set for the version. I don't know if this file was generated with the same package, but just pointing it in case it helps.
The file is the one in `resources/templates/dvdt.linker.xml`.

**Comment by David-Cadmart** [comment]
Can this be reopened? It is still not solved.

**Comment by Power-Maverick** [comment]
This should be resolved now
