### ISSUE TITLE
[Bug]: Cannot make connection after enabled MFA

### ISSUE THREAD

**Issue by emibanana** [Power-Maverick/DataverseDevTools-VSCode#174]
### What happened?

Cannot make connection after enabled MFA. I am pretty sure I typed the correct password and username but i dont get a prompt to input my MFA, very annoying and it just straight away go to fail. MFA is very common practice please fix!

### What version of the tool are you using?

v2.2.0

### What version of Visual Studio Code are you running?

1.85.2

### Any relevant session id from VSCode?

dd974e4a-9da3-4804-825d-bcad0b149c301729167068154

### Relevant log output

```shell
VSCode version: 1.85.2. 
Extension version: 2.2.0. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Use any other type of connection when MFA is enabled. MFA dont work on username and password and that is by design from Microsoft.
