### ISSUE TITLE
Unable to connect, no error details given

### ISSUE THREAD

**Issue by ChrisAdamsUK** [Power-Maverick/DataverseDevTools-VSCode#192]
### What happened?

error appears when tring to connect to environment, and connection is not made. Expected connection to be made and icon to go green

### What version of the tool are you using?

v2.2.1

### Any relevant session id from VSCode?

ff8ebe37-336d-45dd-b4c3-479885543d281731926828184

### Relevant log output

```shell
VSCode version: 1.95.3. 
Extension version: 2.2.1. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
I wasnt able to capture lot of details from the error produced. Can you please share the following:
- What type of login did you use?
- Does your environment has MFA enabled?
- Have you tried using any other login method?

This will help me isolate the issue. Thanks.

**Comment by ChrisAdamsUK** [comment]
After removing the connection and reading the issue resolved
