### ISSUE TITLE
[Bug]: Unable to connect - Error occured - undefined

### ISSUE THREAD

**Issue by thomas-schiller** [Power-Maverick/DataverseDevTools-VSCode#193]
### What happened?

After creation of the connection I see the error message "Dataverse DevTools: Error occured - undefined. Pease report it on GitHub".
I am using Username/Password combination.

### What version of the tool are you using?

v2.2.1

### What version of Visual Studio Code are you running?

1.95.3 (Universal)

**Comment by Power-Maverick** [comment]
Does your Dataverse instance needs MFA. If yes, username/password will not work; please use any other login type. Closing the issue; if this is incorrect please reopen
