### ISSUE TITLE
[Bug]: Connect Fail

### ISSUE THREAD

**Issue by VinnyDyn** [Power-Maverick/DataverseDevTools-VSCode#2]
### Contact Details

vbasile.azur3@outlook.com

### What happened?

Hi Danish, first congrats by this amazing job!
When I try to connect this error is displayed.

![image](https://user-images.githubusercontent.com/36446614/129116856-43216ad7-5352-4ba5-ae40-127adc363756.png)

More details about the VSCode

![image](https://user-images.githubusercontent.com/36446614/129116961-0041cdaa-fe4b-4017-8ca6-141184bf2d83.png)

### What version of the tool are you using?

0.0.4

### What version of Visual Studio Code are you running?

1.59

**Comment by Power-Maverick** [comment]
Do you see the explorer as shown below or do you get an error even before?
If you are able to see the explorer at which point do you get an error exactly?

![image](https://user-images.githubusercontent.com/36135520/129117405-0f3097e0-23e3-49fc-bfe7-ca4d27e8f686.png)

**Comment by Backstergeek** [comment]
Hi Danish,
I am seeing this issue on MacOS but it's working fine on Windows

**Comment by Power-Maverick** [comment]
Ah that explains it. I don't have a MacOS to test. I am excepting PRs so anyone with MacOS wanna test and fix it please do.

**Comment by Backstergeek** [comment]
I know that the Power Platform VS Code Extension has a similar problem where you can't use Username/Password to create a connection.
But If you use the ClientId/Secret option it works

**Comment by Backstergeek** [comment]
That makes sense.

Looking forward to trying that out.

Other then this small issue (for Mac users) it's a great tool I have been looking for one like this for quite some time so thanks :)

**Comment by DavidBreathe** [comment]
I have the same issue. Does it support multi factor authentication login to the dataverse environment?

**Comment by Power-Maverick** [comment]
No not yet. But I am hoping to provide that support for v1.0

**Comment by Power-Maverick** [comment]
Just released version `1.0.0` which has the ability to use Microsoft Login Prompt that will resolve most of the authentication issues. There might be some login issues as each company's authentication configurations are different. Please log a new issue so I am aware of it. For now, closing this issue as the new version is resolving this issue.

@thomassandsor & @DavidBreathe try out the multi-factor auth and lemme know if it works; as it did for me.
