### ISSUE TITLE
[Bug]: Error in connectDataverse 

### ISSUE THREAD

**Issue by YasinGo** [Power-Maverick/DataverseDevTools-VSCode#201]
### What happened?

Cannot connect to the environment.

### What version of the tool are you using?

v2.2.1

### Any relevant session id from VSCode?

acd4a751-23ed-4028-946d-a8819cb859241733908322778

### Relevant log output

```shell
VSCode version: 1.95.3. 
Extension version: 2.2.1. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: Timeout waiting for code. 
Error stack: Error: Timeout waiting for code
	at Timeout.<anonymous> (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:771606)
	at listOnTimeout (node:internal/timers:581:17)
	at process.processTimers (node:internal/timers:519:7).
```

**Comment by Power-Maverick** [comment]
When you use MSFT login it will open a login screen on a browser for you to authenticate. Looks like you did not authenticate yourself on the browser and the process timed out. This is an expected behavior. Please let me know if that is not the case.

**Comment by YasinGo** [comment]
I get the MSFT login screen and I am logging in correctly like every time I did before, but now when I want to upload and publish my code, following error appears:

VSCode version: 1.96.0.
Extension version: 2.2.1.
Error occured in uploadWebResource command.
Error code: undefined.
Error message: Cannot set properties of undefined (setting '@_version').
Error stack: TypeError: Cannot set properties of undefined (setting '@_version')
      at t.xmlToJSON (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:801897)
      at t.WebResourceHelper.<anonymous> (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:762308)
      at Generator.next (<anonymous>)
      at o (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:751513).
________________________________
Von: Danish Naglekar ***@***.***>
Gesendet: Montag, 16. Dezember 2024 14:16
An: Power-Maverick/DataverseDevTools-VSCode ***@***.***>
Cc: YasinGo ***@***.***>; Author ***@***.***>
Betreff: Re: [Power-Maverick/DataverseDevTools-VSCode] [Bug]: Error in connectDataverse (Issue #201)


When you use MSFT login it will open a login screen on a browser for you to authenticate. Looks like you did not authenticate yourself on the browser and the process timed out. This is an expected behavior. Please let me know if that is not the case.

**Comment by Power-Maverick** [comment]
Yes there is an open bug for that #200
I'll close out this bug and you can check the status on the other. Should be resolved soon.
