### ISSUE TITLE
[Feature]: PowerApps Checker passing - equality optimisation

### ISSUE THREAD

**Issue by filcole** [Power-Maverick/DataverseDevTools-VSCode#23]
### Is your feature request related to a problem?

No

### Describe the problem?

Does webpack optimisation cause the solution checker to fail?  I've had to avoid that previously when testing webpack., see here: https://github.com/scottdurow/building-power-apps-js-webresources/pull/4

### Provide a solution or an idea you would like to see in the tool?

See PR here https://github.com/scottdurow/building-power-apps-js-webresources/pull/4 for a potential fix.

**Comment by Power-Maverick** [comment]
Released in v1.1.6. Thanks @filcole
