### ISSUE TITLE
[Feature]: Ability to have option to load TS project with or without WebPack

### ISSUE THREAD

**Issue by Power-Maverick** [Power-Maverick/DataverseDevTools-VSCode#25]
### Discussed in https://github.com/Power-Maverick/DataverseDevTools-VSCode/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **cfernandezcsp** October 28, 2021</sup>
Can I ask a stupid question?

Why is the tool including WebPack when creating the project?

Wouldn't it be more flexible if only Typescript is included and leave the decision over the other tools to the user?</div>

**Comment by Power-Maverick** [comment]
Updated the extension with the ability for users to choose which template they want. Give it a try. (v1.1.4)

**Comment by cfernandezcsp** [comment]
@Power-Maverick  Tested and it works phenomenally! You're a rockstar!
