### ISSUE TITLE
[Bug]: Askingn for permissions while connecting to dataverse

### ISSUE THREAD

**Issue by singh-harendra** [Power-Maverick/DataverseDevTools-VSCode#30]
### Contact Details

harendra121

### What happened?

While connecting to Dataverse, it prompts following errror msg.

Dataverse DevTools needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it. 

I am using account with System Administrator access, not sure what resource permissions it's requesting.

### What version of the tool are you using?

1.1.6

### What version of Visual Studio Code are you running?

1.62.3

### Relevant log output

```shell
Dataverse DevTools needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.
```

**Comment by Power-Maverick** [comment]
The Microsoft Login Prompt uses a Public App registered in Azure AD hence it will need approval from Azure admin. I have also released the 3rd type of authentication using client id/secret. This is released in version 1.1.9.
