### ISSUE TITLE
[Feature]:  App Registration for MFA environments

### ISSUE THREAD

**Issue by thomassandsor** [Power-Maverick/DataverseDevTools-VSCode#31]
### Is your feature request related to a problem?

No

### Describe the problem?

Would be nice to connect to dataverse with the App Registration + Client Secret. Use the same type of credentials for XrmToolBox, so it would be easy to setup here also if possible :)

The authentication of the app seems to be a harder challenge at some customers..

**Comment by Power-Maverick** [comment]
@thomassandsor I have added a new setting to enable early-access preview. Check out the details [here](https://github.com/Power-Maverick/DataverseDevTools-VSCode#-early-access-preview). 

Do you wanna help me test this?

**Comment by thomassandsor** [comment]
![image](https://user-images.githubusercontent.com/33664322/145904818-0c019553-614c-4343-8885-2ff926272541.png)

After adding the Appid and secret, I was forwarded to this URL.. I was not able to login here, and not really sure what it is trying to achieve with that login

**Comment by Power-Maverick** [comment]
Please follow the instructions on setting up the registered app mentioned [here](https://github.com/Power-Maverick/DataverseDevTools-VSCode#-early-access-preview)

**Comment by thomassandsor** [comment]
Added the new forwarding, and waiting for IT to approve the app. Will let you know once it is approved

So just a little curious. For the XRMToolBox and DevOpsPipelines we only need to use App ID and Client Secret.. Why do we have to add the extra "app approval in azure" thing here? :)

**Comment by Power-Maverick** [comment]
@thomassandsor fixed that issue. Can you try with the new version?

**Comment by thomassandsor** [comment]
Tested out the new version, and this time the App ID, Client Secret and Tennant ID worked without any extra promts:) 

Now I have the connection working, and I feel I might have lots of other questions!:) hehe.. Will DM you a few, and if you want them to be public, I can put them out here.

**Comment by Power-Maverick** [comment]
Made client id/secret authentication GA in version 1.1.9
