### ISSUE TITLE
[Feature]: Get latest version of webresource from Dynamics

### ISSUE THREAD

**Issue by thomassandsor** [Power-Maverick/DataverseDevTools-VSCode#32]
### Is your feature request related to a problem?

No

### Describe the problem?

At times one might not be sure if the DevOps/GitHub version of the webresource is the latest. In these cases it would nice to get the latest version from Dynamics / DataVerse. 

I.E if one would right click the webresource and "get latest from DV"

**Comment by Power-Maverick** [comment]
When using TypeScript; if we get the latest JavaScript that is deployed to Dataverse then will need to reverse-engineer the code to the TS which won't be ideal. What I can do is provide a way to compare the files between local and server. Does that sound reasonable?

**Comment by Power-Maverick** [comment]
This is added as a Preview feature. So if you have the "Early Access Preview" enabled you should be able to compare the web resources. Check out the details [here](https://github.com/Power-Maverick/DataverseDevTools-VSCode#-early-access-preview). Please let me know how was your testing with this new feature.

**Comment by thomassandsor** [comment]
This function seemed to work quite well!! More than enough for what I would normally need 🙌
