### ISSUE TITLE
[Bug]: Upload and Publish

### ISSUE THREAD

**Issue by thomassandsor** [Power-Maverick/DataverseDevTools-VSCode#33]
### Is your feature request related to a problem?

No

### Describe the problem?

Would be nice to update and publish webresource in one single action right clicking the webresource.

**Comment by Power-Maverick** [comment]
One-click upload and publish already exists (see image below) but seems like that option sometimes don't show up. Looking into it now.
![image](https://user-images.githubusercontent.com/36135520/147573177-57a12c01-6ddb-4485-b753-0500588cfb2e.png)

**Comment by thomassandsor** [comment]
Ohh.. That does answer my question then. I think it should be "Upload and Publish Web Resource" just to be certain that it also publishes:) Thought I also had to publish.. Great stuff..

**Comment by Power-Maverick** [comment]
@thomassandsor please retest this with the new release. Closing the issue for now but if you still see issues with it please feel free to reopen this bug. Thanks.
