### ISSUE TITLE
[Bug]: Create plugin failes

### ISSUE THREAD

**Issue by rappen** [Power-Maverick/DataverseDevTools-VSCode#4]
### What happened?

Running: 
![image](https://user-images.githubusercontent.com/2572253/129179934-40b40d96-e64d-4b3a-be06-ffd57b9926d6.png)

Got this:
![image](https://user-images.githubusercontent.com/2572253/129179640-53ec0be2-29b2-4097-a85f-eb4caf829211.png)

### What version of the tool are you using?

Don't know, I guess 0.0.4

### What version of Visual Studio Code are you running?

1.59.0

**Comment by Power-Maverick** [comment]
Interesting that feature is not implemented yet and should not have shown up on the command pallet. This is again a planned feature to add; there are some issues with it as of now when using `pac cli` command which I need to resolve. 

https://github.com/Power-Maverick/DataverseDevTools-VSCode#-planned-features

**Comment by JoshSmithXRM** [comment]
Created PR #6 to resolve this issue

**Comment by Power-Maverick** [comment]
It Will get fixed in 0.0.5 version
