### ISSUE TITLE
[Bug]: Matching javascript files local to DV javascript

### ISSUE THREAD

**Issue by thomassandsor** [Power-Maverick/DataverseDevTools-VSCode#45]
### What happened?

Thought I had seen a function for this earlier, but how do I connect the files local to DV without having to rename the files either local or DV? 

![image](https://user-images.githubusercontent.com/33664322/148379138-178df560-763f-491d-bb1e-36a5d092c8f8.png)

I thought I had a right click option earlier with matching that created the matching file?:)

This is for the files that don't get a match in the smart match, and would like to update the dvdt.linnker.xml

### What version of the tool are you using?

Latest beta

**Comment by Power-Maverick** [comment]
Acknowledged the drawback of the current implementation. Will add an ability to right-click and link the files as well.
