### ISSUE TITLE
[Bug]: Could not create the webpack TS Project 

### ISSUE THREAD

**Issue by SatkunamSuganthar** [Power-Maverick/DataverseDevTools-VSCode#57]
### Contact Details

ssuganthar@gmail.com

### What happened?

When I click on the Create Dataverse TS Project option in the Dev Tools, it normally ask to create the name space and project type as Typescript only Or webpack. it is no longer working in current version.

I have used this fucntionality in the past in oldder versions and created the webpack TS Project. 

### What version of the tool are you using?

2.0.2

### What version of Visual Studio Code are you running?

1.63.2

**Comment by SatkunamSuganthar** [comment]
@Power-Maverick  FYI When I installed the version of 1.1.11, It works perfectly. 

![image](https://user-images.githubusercontent.com/97066265/151699345-3be2d0ff-f35a-4f91-ac65-8a1772cd9973.png)

**Comment by Power-Maverick** [comment]
Thank you for reporting the issue. I will try to replicate the bug on my end and will report back.

**Comment by Power-Maverick** [comment]
Resolved in v2.0.3
