### ISSUE TITLE
[Bug]: Unable to connect toi instance

### ISSUE THREAD

**Issue by AlwaysDora** [Power-Maverick/DataverseDevTools-VSCode#59]
### Contact Details

dorababu.manyam@microsoft.com

### What happened?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/69141183/153280424-45fc4df2-74d4-4516-9ded-c54e4aada9cc.png">

### What version of the tool are you using?

2.0.4

### What version of Visual Studio Code are you running?

1.63.2

### Relevant log output

```shell
attached image for reference
```

**Comment by Power-Maverick** [comment]
May I get more information as to the steps you choose during the connection that resulted in an error?
