### ISSUE TITLE
[Feature]: Use Auth Profiles from 'Power Platform Tools' extension

### ISSUE THREAD

**Issue by filcole** [Power-Maverick/DataverseDevTools-VSCode#65]
### Contact Details

Twitter: @EffEyeEll  LinkedIn: linkedin.com/in/filcole

### Is your feature request related to a problem?

No

### Describe the problem?

Currently, we must authenticate again in Dataverse Dev Tools as well as in  Microsofts (now GA) Power Platform Tools extension.

### Provide a solution or an idea you would like to see in the tool?

It would be great to be able to use the authentication profiles that might already exist if someone has previously setup a provile via the Power Platform CLI Tooling

A small quality of life improvement. 
Thank you for all the work you've put into this tool

**Comment by Power-Maverick** [comment]
This would have to assume that Power Platform CLI is installed. Will try to see if I can first identify its installation status and then prompt additional options during connection creation.
