### ISSUE TITLE
[Bug]: Unable to connect CE using VS Code extension

### ISSUE THREAD

**Issue by Amritesh2008** [Power-Maverick/DataverseDevTools-VSCode#70]
### What happened?

[Bug]: Unable to connect CE using VS Code extension

![image](https://user-images.githubusercontent.com/24248757/171032260-91fc2690-002d-4041-a13c-1950340958db.png)

### What version of the tool are you using?

1.67.2

### What version of Visual Studio Code are you running?

1.67.2

**Comment by Power-Maverick** [comment]
Closing as stale
