### ISSUE TITLE
[Bug]: Can't connect using any other method than ClientId/Secret  

### ISSUE THREAD

**Issue by siggipop** [Power-Maverick/DataverseDevTools-VSCode#71]
### What happened?

As the title says, I can't create connection to Dataverse with any other method than ClientId/Secret. It just gives an error, with no details to what is wrong.

### What version of the tool are you using?

v2.0.5

### What version of Visual Studio Code are you running?

1.67.2

### Relevant log output

```shell
Dataverse DevTools: Error occured.
```

**Comment by Power-Maverick** [comment]
Sorry for the delayed response as I might have mistakenly skipped this issue. Were you able to resolve the issue with the connection?

If not I do have a question - did your environment have MFA enabled?

**Comment by siggipop** [comment]
Yeas, MFA is enabled in our environment.

**Comment by Power-Maverick** [comment]
Unfortunately, if MFA is enabled username/password won't work

**Comment by Power-Maverick** [comment]
With MFA enabled below are the only options:
1. Client Id & Secret
2. Microsoft Login Prompt
3. Azure

If you still face any issues with any of the above-said connections please create a separate bug. Marking this as resolved. Thanks.
