### ISSUE TITLE
[Feature]: Web Resources smart match

### ISSUE THREAD

**Issue by filcole** [Power-Maverick/DataverseDevTools-VSCode#72]
### Contact Details

@effEyeEll

### Is your feature request related to a problem?

Yes

### Describe the problem?

Hi @Power-Maverick, 

Just kicking the typres of Web Resources smart match.  Looks really interesting. I noticed the following things that I thought might interesting to consider improving (sorry I don't have time to contribute right now!)

The smart match config file is a single XML line, if it was pretty printed then it would make it easier to understand, and would be easier to (git) merge if multiple people are working with it in git. 

![image](https://user-images.githubusercontent.com/6078398/185509504-d07a307d-def9-4551-9410-6ae132c9a1c5.png)

**Comment by Power-Maverick** [comment]
Good idea 👍 
Will check the feasibility

**Comment by Power-Maverick** [comment]
Couldn't find any method to invoke the default formatter when the file is created. Have asked the question [here](https://stackoverflow.com/questions/73439180/auto-format-a-newly-created-file-using-vs-code-extension-api). Let's see if I get any good response.

In the meantime, you can right-click and select format before checking-in the file.

**Comment by filcole** [comment]
I had a quick view of the code.  Is a JSON object being converted to XML using `jsonToXML` ? 
https://github.com/Power-Maverick/DataverseDevTools-VSCode/blob/f60b211f3351e30b0d6b1c37ce4780d60a736669/src/utils/Parsers.ts#L18

if so then setting `format: true` might do the trick.
https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/3.XMLBuilder.md#format

**Comment by Power-Maverick** [comment]
You are a lifesaver. I totally forgot about that method

**Comment by Power-Maverick** [comment]
This should be released in v2.0.8
