### ISSUE TITLE
[Feature]: Support to upload and publish .resx files

### ISSUE THREAD

**Issue by mcoomans** [Power-Maverick/DataverseDevTools-VSCode#74]
### Contact Details

marc.coomans@itineris.net

### Is your feature request related to a problem?

No

### Provide a solution or an idea you would like to see in the tool?

Would like to see support for linking, uploading, and publishing .resx files . 
Resx files are often changed  together with  TS/JS files when doing Dynamics 365 customization work for international clients.

**Comment by pstumpe** [comment]
+1
Would be great as this is currently the one thing I'm missing.
