### ISSUE TITLE
[Bug]: Cannot find module '@azure/identity-vscode'

### ISSUE THREAD

**Issue by siggipop** [Power-Maverick/DataverseDevTools-VSCode#77]
### Contact Details

siggi_pop@hotmail.com

### What happened?

All of a sudden DataversDevTools-VSCode can´t connect to Dataverse! 
Nothing happens when selecting button "Create New Connection" 

In VS Code developer tools console log, I notice following  error when pushing button: 
command 'dvdt.explorer.connections.addConnection' not found: Error: command 'dvdt.explorer.connections.addConnection' not found   

I did try uninstalling/installing extension. 

Then I noticed this error on VS Code console log: 
Activating extension 'danish-naglekar.dataverse-devtools' failed: Cannot find module '@azure/identity-vscode'

I tried:
re-installing @azure/identity (latest)
re-installing @azure/identity-vscode (latest)
npm install
downgrading azure-functions-core-tools  (version 2 - i'm out of ideas )

Then I tried downgrading from ^3.0.0 to @azure/identity 2.1.0 that didn't help.... or actually maybe it did?
Ok that's weird - now the extension works again as I'm writing this, and the log errors are gone!? and I'm back to version  @azure/identity 3.0.0

I spent too much time debugging and to write this, that I'm just gonna leave it here. But I guess you it can be closed.

### What version of the tool are you using?

2.0.14 (latest)

### What version of Visual Studio Code are you running?

1.71.2

**Comment by Power-Maverick** [comment]
Looking into it now.

**Comment by Power-Maverick** [comment]
Yes, there were weird issues since the latest release of v2.0.9. The tool worked fine when locally debugging but didn't work when published. So had to release several fixes but v2.0.16 should work as expected. Please update the tool to the latest version and reload the window.
