### ISSUE TITLE
[Feature]: SVG support in web resources

### ISSUE THREAD

**Issue by svingkaer** [Power-Maverick/DataverseDevTools-VSCode#8]
### Contact Details

mads@svingkaer.dk

### Is your feature request related to a problem?

No

### Describe the problem?

Would love to see support for especially .svg web resources

**Comment by Power-Maverick** [comment]
As far as I know, SVGs are not supported by Dataverse. So what are you proposing? Would love to hear your ideas.

**Comment by RobNightingale-LSL** [comment]
I would also like this feature. although images arent updated often it would be nice to be able to publish directly from the DVDT tools
