### ISSUE TITLE
[Bug]: Problem with Microsoft Login Promt

### ISSUE THREAD

**Issue by darkwheel** [Power-Maverick/DataverseDevTools-VSCode#84]
### Contact Details

darkwheeldevelopment@gmail.com

### What happened?

Used the Microsoft Login Prompt to Login as we use MFA in the company and got following error:

> AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope xxxx.crm4.dynamics.com/user_impersonation openid profile offline_access is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

It seems like the scope the login prompt gets is not in a valid format...

Tried this 11/3/22 at 4:45 GMT+1

### What version of the tool are you using?

v2.1.0

### What version of Visual Studio Code are you running?

1.73.0

### Relevant log output

```shell
Dataverse DevTools: Error occured. Please report it on GitHub with the activity you tried to perform along with Date & Time.
```

**Comment by Power-Maverick** [comment]
Can you confirm the URL provided was correct? I am unable to reproduce the issue.
