### ISSUE TITLE
[Bug]: connection with client id + secret only works the first time

### ISSUE THREAD

**Issue by davide-palchetti-bingo** [Power-Maverick/DataverseDevTools-VSCode#85]
### What happened?

Trying to connect to an existing connection does not work, only creating a new connection works.

I'm using client id + secret, here are the connections details if that helps.
![image](https://user-images.githubusercontent.com/103412016/201243132-8c897c99-4f41-4c06-8f0c-5c606ad9bddf.png)

I have not tried any other authentication methods.

### What version of the tool are you using?

v2.1.0

### What version of Visual Studio Code are you running?

1.73.0

**Comment by Power-Maverick** [comment]
Fixed in v2.1.1
