### ISSUE TITLE
[Bug]: Can't connect to environment

### ISSUE THREAD

**Issue by wd21sos** [Power-Maverick/DataverseDevTools-VSCode#86]
### Contact Details

stefan.ossanna@world-direct.at

### What happened?

Connecting via username/password not possible. I always get this error message that an error occurred, but can't take a look into the log what exactly the problem is.

![image](https://user-images.githubusercontent.com/92533241/202179320-27398e5c-55e6-44df-9782-bc852455fa1b.png)

It's been a while since the last login through that connections, so maybe a new update was released in between. I already deleted the extension and reinstalled. Also deleted all connections and tried to add + reconnect, but still the error occurs. It doesn't matter which connection, all my connections are not working.

### What version of the tool are you using?

v2.1.0

### What version of Visual Studio Code are you running?

1.73.1

**Comment by brettofthewild** [comment]
Running into this error as well.

**Comment by ntarakaram1980** [comment]
got the same error and no information

**Comment by Power-Maverick** [comment]
Try with the new version and if the issue persists; please log a new issue as I have added enhanced logging and error reporting so should provide me with better insights. Closing this for now. Thanks.
