### ISSUE TITLE
[Bug]: After deleting a connection reference, if I try to add a new one with same name, I get an error saying it already exists

### ISSUE THREAD

**Issue by uofirob** [Power-Maverick/DataverseDevTools-VSCode#89]
### Contact Details

rob.montague@ey.com

### What happened?

Related to my other issue where I'm unable to connect to a dataverse environment with the application id/client secret when the token expires, I tried to delete the connection and then re-add it.  The issue was even though I deleted the connection, it seems like the name still exists in the back-end.  Please fix the delete procedure to remove that name to allow a re-add with the same name.

### What version of the tool are you using?

v2.1.0

### What version of Visual Studio Code are you running?

1.73.1 (user setup)

**Comment by Power-Maverick** [comment]
Fixed in v2.1.1
