### ISSUE TITLE
[Bug]: Connecting to environment not working

### ISSUE THREAD

**Issue by wd21sos** [Power-Maverick/DataverseDevTools-VSCode#92]
### What happened?

Connecting via username/password still not possible. After the version update the error message changed, but the problem still exists, that I can't connect to any environment.

![image](https://user-images.githubusercontent.com/92533241/202988058-5d1eb7c0-a7f2-42c0-a171-da733a934843.png)

The log output was added through creating the bug via the error message. Don't know if that helps.

### What version of the tool are you using?

v2.1.1

### What version of Visual Studio Code are you running?

1.73.1

### Any relevant session id from VSCode?

acfaf457-e549-442d-85bf-574c00bd8e231669014766144

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by neb-miletic** [comment]
I have exactly same issue. Please help

**Comment by Power-Maverick** [comment]
Can you check with newer versions released? Thanks.
