### ISSUE TITLE
[Bug]: connect error:undefined

### ISSUE THREAD

**Issue by ly520** [Power-Maverick/DataverseDevTools-VSCode#93]
### What happened?

when connect to my online environment, dataverse devtools report an error: Error occured--undefined

im in china,address like  https://xxxxxxx.crm.dynamics.cn , is any question?

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.74.2

### Any relevant session id from VSCode?

f3f36114-51ae-49ab-af1c-e4debd85fc4d1672885333648

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Can you specify which type of authentication method you selected?
