### ISSUE TITLE
[Bug]: Unable to add multiple connections 

### ISSUE THREAD

**Issue by pavanmanideep** [Power-Maverick/DataverseDevTools-VSCode#95]
### What happened?

Unable to create and connect to switch between sources in Dataverse Dev Tools. It says Error occured and report in GIT Hub.

### What version of the tool are you using?

Latest

### What version of Visual Studio Code are you running?

Latest

### Any relevant session id from VSCode?

5cf7d146-9ade-4ed2-afe4-b1bc790f42aa1674788605772

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Can you specify which type of authentication method you selected?

**Comment by pavanmanideep** [comment]
Hi Danish, I have used Built in authentication for Dataverse dev tools...However I faced this long back in Jan, not now, thanks for response....
