### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jazucco-oeis** [Power-Maverick/DataverseDevTools-VSCode#96]
### What happened?

Attempted to connect to previously defined connection and it resulted in this error. 

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.75.0

### Any relevant session id from VSCode?

7813c241-ed59-4a35-9bcc-1da9d8074aa71675809126724

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by Power-Maverick** [comment]
Can you provide more info please?
